### ISSUE TITLE
Dispensers can't be enchanted in survival

### ISSUE THREAD

**Issue by FubyCutie** [SkyeEmmyMods/CarpetEnhancedDispensers#18]
Dispensers can be combined in an anvil with enchanted books in creative, but not in survival

**Comment by AdelinaM17n** [comment]
This can be fixed by mixining into `AnvilScreenHandler`'s `updateResult` method and adding an exception there.

Easiest way would be to redirect `Lnet/minecraft/entity/player/PlayerAbilities;creativeMode:Z` in there and return true if it is a dispenser. (or ordinal 2 of `Lnet/minecraft/item/ItemStack;isOf(Lnet/minecraft/item/Item;)Z` )

Also sorry if you wanted to do this on your own and I just jumped in the middle, was bored and going through my gh feed xd

**Comment by FubyCutie** [comment]
I was considering a few approaches, including that one, but forgot to write them here, I think injecting into the head of isSuitableItem for the enchantment is going to be a better approach, as it is more general, also rather than returning true, the plan would be to check if the enchantment being used is one with a specified dispenser behaviour

**Comment by AdelinaM17n** [comment]
I am guessing you meant `isAcceptableItem` in enchantment class (I don't use yarn mappings, I just translate mojmaps to yarn before talking)? ye that would be a better and more stable approach, totally missed it.

Also did mean to say you can use those redirects to do the checks and return true but ig my phrasing was poor. Anyways your approach is superior because well it does the filtering for you, and injects are more stable.
